// Date: 6/3/2018 1:55:46 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hexopygate.Telgttatium.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWoodenType2Fence extends ModelBase
{
  //fields
    ModelRenderer StartPlank;
    ModelRenderer Plank1;
    ModelRenderer Plank2;
    ModelRenderer EndPlank;
    ModelRenderer Bar2;
    ModelRenderer Bar;
    ModelRenderer Bar3;
  
  public ModelWoodenType2Fence()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      StartPlank = new ModelRenderer(this, 0, 0);
      StartPlank.addBox(0F, 0F, 0F, 3, 15, 1);
      StartPlank.setRotationPoint(-8F, 9F, 0F);
      StartPlank.setTextureSize(64, 32);
      StartPlank.mirror = true;
      setRotation(StartPlank, 0F, 0F, 0F);
      Plank1 = new ModelRenderer(this, 12, 0);
      Plank1.addBox(0F, 0F, 0F, 4, 15, 1);
      Plank1.setRotationPoint(-4F, 9F, 0F);
      Plank1.setTextureSize(64, 32);
      Plank1.mirror = true;
      setRotation(Plank1, 0F, 0F, 0F);
      Plank2 = new ModelRenderer(this, 12, 0);
      Plank2.addBox(0F, 0F, 0F, 4, 15, 1);
      Plank2.setRotationPoint(1F, 9F, 0F);
      Plank2.setTextureSize(64, 32);
      Plank2.mirror = true;
      setRotation(Plank2, 0F, 0F, 0F);
      EndPlank = new ModelRenderer(this, 25, 0);
      EndPlank.addBox(0F, 0F, 0F, 2, 15, 1);
      EndPlank.setRotationPoint(6F, 9F, 0F);
      EndPlank.setTextureSize(64, 32);
      EndPlank.mirror = true;
      setRotation(EndPlank, 0F, 0F, 0F);
      Bar2 = new ModelRenderer(this, 0, 18);
      Bar2.addBox(0F, 0F, 0F, 16, 1, 1);
      Bar2.setRotationPoint(-8F, 12F, 1F);
      Bar2.setTextureSize(64, 32);
      Bar2.mirror = true;
      setRotation(Bar2, 0F, 0F, 0F);
      Bar = new ModelRenderer(this, 0, 18);
      Bar.addBox(0F, 0F, 0F, 16, 1, 1);
      Bar.setRotationPoint(-8F, 10F, 1F);
      Bar.setTextureSize(64, 32);
      Bar.mirror = true;
      setRotation(Bar, 0F, 0F, 0F);
      Bar3 = new ModelRenderer(this, 0, 22);
      Bar3.addBox(0F, 0F, 0F, 16, 3, 1);
      Bar3.setRotationPoint(-8F, 21F, 1F);
      Bar3.setTextureSize(64, 32);
      Bar3.mirror = true;
      setRotation(Bar3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    StartPlank.render(f5);
    Plank1.render(f5);
    Plank2.render(f5);
    EndPlank.render(f5);
    Bar2.render(f5);
    Bar.render(f5);
    Bar3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
