// Date: 6/3/2018 1:44:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hexopygate.Telgttatium.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDecoFence extends ModelBase
{
  //fields
    ModelRenderer Bar;
    ModelRenderer upperleft;
    ModelRenderer upperright;
    ModelRenderer uppermid;
    ModelRenderer Bottomleft;
    ModelRenderer bottomright;
    ModelRenderer bottommid;
    ModelRenderer Bar1;
    ModelRenderer upperleft1;
    ModelRenderer uppermid1;
    ModelRenderer upperright1;
    ModelRenderer Bottomleft1;
    ModelRenderer bottommid1;
    ModelRenderer bottomright1;
    ModelRenderer Bar2;
    ModelRenderer upperleft2;
    ModelRenderer uppermid2;
    ModelRenderer upperright2;
    ModelRenderer Bottomleft2;
    ModelRenderer bottommid2;
    ModelRenderer bottomright2;
    ModelRenderer Bar3;
    ModelRenderer upperleft3;
    ModelRenderer uppermid3;
    ModelRenderer upperright3;
    ModelRenderer Bottomleft3;
    ModelRenderer bottommid3;
    ModelRenderer bottomright3;
  
  public ModelDecoFence()
  {
    textureWidth = 4;
    textureHeight = 17;
    
      Bar = new ModelRenderer(this, 0, 0);
      Bar.addBox(-0.5F, -7.5F, -0.5F, 1, 16, 1);
      Bar.setRotationPoint(-7.5F, 15.5F, 0F);
      Bar.setTextureSize(4, 17);
      Bar.mirror = true;
      setRotation(Bar, 0F, 0F, 0F);
      upperleft = new ModelRenderer(this, 0, 0);
      upperleft.addBox(0F, 0F, 0F, 1, 1, 1);
      upperleft.setRotationPoint(-7F, 11F, -0.5F);
      upperleft.setTextureSize(4, 17);
      upperleft.mirror = true;
      setRotation(upperleft, 0F, 0F, 0F);
      upperright = new ModelRenderer(this, 0, 0);
      upperright.addBox(0F, 0F, 0F, 1, 1, 1);
      upperright.setRotationPoint(-5F, 11F, -0.5F);
      upperright.setTextureSize(4, 17);
      upperright.mirror = true;
      setRotation(upperright, 0F, 0F, 0F);
      uppermid = new ModelRenderer(this, 0, 0);
      uppermid.addBox(0F, 0F, 0F, 1, 1, 1);
      uppermid.setRotationPoint(-6F, 10F, -0.5F);
      uppermid.setTextureSize(4, 17);
      uppermid.mirror = true;
      setRotation(uppermid, 0F, 0F, 0F);
      Bottomleft = new ModelRenderer(this, 0, 0);
      Bottomleft.addBox(0F, 0F, 0F, 1, 1, 1);
      Bottomleft.setRotationPoint(-7F, 20F, -0.5F);
      Bottomleft.setTextureSize(4, 17);
      Bottomleft.mirror = true;
      setRotation(Bottomleft, 0F, 0F, 0F);
      bottomright = new ModelRenderer(this, 0, 0);
      bottomright.addBox(0F, 0F, 0F, 1, 1, 1);
      bottomright.setRotationPoint(-5F, 20F, -0.5F);
      bottomright.setTextureSize(4, 17);
      bottomright.mirror = true;
      setRotation(bottomright, 0F, 0F, 0F);
      bottommid = new ModelRenderer(this, 0, 0);
      bottommid.addBox(0F, 0F, 0F, 1, 1, 1);
      bottommid.setRotationPoint(-6F, 21F, -0.5F);
      bottommid.setTextureSize(4, 17);
      bottommid.mirror = true;
      setRotation(bottommid, 0F, 0F, 0F);
      Bar1 = new ModelRenderer(this, 0, 0);
      Bar1.addBox(-0.5F, -7.5F, -0.5F, 1, 16, 1);
      Bar1.setRotationPoint(-3.5F, 15.5F, 0F);
      Bar1.setTextureSize(4, 17);
      Bar1.mirror = true;
      setRotation(Bar1, 0F, 0F, 0F);
      upperleft1 = new ModelRenderer(this, 0, 0);
      upperleft1.addBox(0F, 0F, 0F, 1, 1, 1);
      upperleft1.setRotationPoint(5F, 11F, -0.5F);
      upperleft1.setTextureSize(4, 17);
      upperleft1.mirror = true;
      setRotation(upperleft1, 0F, 0F, 0F);
      uppermid1 = new ModelRenderer(this, 0, 0);
      uppermid1.addBox(0F, 0F, 0F, 1, 1, 1);
      uppermid1.setRotationPoint(6F, 10F, -0.5F);
      uppermid1.setTextureSize(4, 17);
      uppermid1.mirror = true;
      setRotation(uppermid1, 0F, 0F, 0F);
      upperright1 = new ModelRenderer(this, 0, 0);
      upperright1.addBox(0F, 0F, 0F, 1, 1, 1);
      upperright1.setRotationPoint(7F, 11F, -0.5F);
      upperright1.setTextureSize(4, 17);
      upperright1.mirror = true;
      setRotation(upperright1, 0F, 0F, 0F);
      Bottomleft1 = new ModelRenderer(this, 0, 0);
      Bottomleft1.addBox(0F, 0F, 0F, 1, 1, 1);
      Bottomleft1.setRotationPoint(5F, 20F, -0.5F);
      Bottomleft1.setTextureSize(4, 17);
      Bottomleft1.mirror = true;
      setRotation(Bottomleft1, 0F, 0F, 0F);
      bottommid1 = new ModelRenderer(this, 0, 0);
      bottommid1.addBox(0F, 0F, 0F, 1, 1, 1);
      bottommid1.setRotationPoint(6F, 21F, -0.5F);
      bottommid1.setTextureSize(4, 17);
      bottommid1.mirror = true;
      setRotation(bottommid1, 0F, 0F, 0F);
      bottomright1 = new ModelRenderer(this, 0, 0);
      bottomright1.addBox(0F, 0F, 0F, 1, 1, 1);
      bottomright1.setRotationPoint(7F, 20F, -0.5F);
      bottomright1.setTextureSize(4, 17);
      bottomright1.mirror = true;
      setRotation(bottomright1, 0F, 0F, 0F);
      Bar2 = new ModelRenderer(this, 0, 0);
      Bar2.addBox(-0.5F, -7.5F, -0.5F, 1, 16, 1);
      Bar2.setRotationPoint(0.5F, 15.5F, 0F);
      Bar2.setTextureSize(4, 17);
      Bar2.mirror = true;
      setRotation(Bar2, 0F, 0F, 0F);
      upperleft2 = new ModelRenderer(this, 0, 0);
      upperleft2.addBox(0F, 0F, 0F, 1, 1, 1);
      upperleft2.setRotationPoint(-3F, 11F, -0.5F);
      upperleft2.setTextureSize(4, 17);
      upperleft2.mirror = true;
      setRotation(upperleft2, 0F, 0F, 0F);
      uppermid2 = new ModelRenderer(this, 0, 0);
      uppermid2.addBox(0F, 0F, 0F, 1, 1, 1);
      uppermid2.setRotationPoint(-2F, 10F, -0.5F);
      uppermid2.setTextureSize(4, 17);
      uppermid2.mirror = true;
      setRotation(uppermid2, 0F, 0F, 0F);
      upperright2 = new ModelRenderer(this, 0, 0);
      upperright2.addBox(0F, 0F, 0F, 1, 1, 1);
      upperright2.setRotationPoint(-1F, 11F, -0.5F);
      upperright2.setTextureSize(4, 17);
      upperright2.mirror = true;
      setRotation(upperright2, 0F, 0F, 0F);
      Bottomleft2 = new ModelRenderer(this, 0, 0);
      Bottomleft2.addBox(0F, 0F, 0F, 1, 1, 1);
      Bottomleft2.setRotationPoint(-3F, 20F, -0.5F);
      Bottomleft2.setTextureSize(4, 17);
      Bottomleft2.mirror = true;
      setRotation(Bottomleft2, 0F, 0F, 0F);
      bottommid2 = new ModelRenderer(this, 0, 0);
      bottommid2.addBox(0F, 0F, 0F, 1, 1, 1);
      bottommid2.setRotationPoint(-2F, 21F, -0.5F);
      bottommid2.setTextureSize(4, 17);
      bottommid2.mirror = true;
      setRotation(bottommid2, 0F, 0F, 0F);
      bottomright2 = new ModelRenderer(this, 0, 0);
      bottomright2.addBox(0F, 0F, 0F, 1, 1, 1);
      bottomright2.setRotationPoint(-1F, 20F, -0.5F);
      bottomright2.setTextureSize(4, 17);
      bottomright2.mirror = true;
      setRotation(bottomright2, 0F, 0F, 0F);
      Bar3 = new ModelRenderer(this, 0, 0);
      Bar3.addBox(-0.5F, -7.5F, -0.5F, 1, 16, 1);
      Bar3.setRotationPoint(4.5F, 15.5F, 0F);
      Bar3.setTextureSize(4, 17);
      Bar3.mirror = true;
      setRotation(Bar3, 0F, 0F, 0F);
      upperleft3 = new ModelRenderer(this, 0, 0);
      upperleft3.addBox(0F, 0F, 0F, 1, 1, 1);
      upperleft3.setRotationPoint(1F, 11F, -0.5F);
      upperleft3.setTextureSize(4, 17);
      upperleft3.mirror = true;
      setRotation(upperleft3, 0F, 0F, 0F);
      uppermid3 = new ModelRenderer(this, 0, 0);
      uppermid3.addBox(0F, 0F, 0F, 1, 1, 1);
      uppermid3.setRotationPoint(2F, 10F, -0.5F);
      uppermid3.setTextureSize(4, 17);
      uppermid3.mirror = true;
      setRotation(uppermid3, 0F, 0F, 0F);
      upperright3 = new ModelRenderer(this, 0, 0);
      upperright3.addBox(0F, 0F, 0F, 1, 1, 1);
      upperright3.setRotationPoint(3F, 11F, -0.5F);
      upperright3.setTextureSize(4, 17);
      upperright3.mirror = true;
      setRotation(upperright3, 0F, 0F, 0F);
      Bottomleft3 = new ModelRenderer(this, 0, 0);
      Bottomleft3.addBox(0F, 0F, 0F, 1, 1, 1);
      Bottomleft3.setRotationPoint(1F, 20F, -0.5F);
      Bottomleft3.setTextureSize(4, 17);
      Bottomleft3.mirror = true;
      setRotation(Bottomleft3, 0F, 0F, 0F);
      bottommid3 = new ModelRenderer(this, 0, 0);
      bottommid3.addBox(0F, 0F, 0F, 1, 1, 1);
      bottommid3.setRotationPoint(2F, 21F, -0.5F);
      bottommid3.setTextureSize(4, 17);
      bottommid3.mirror = true;
      setRotation(bottommid3, 0F, 0F, 0F);
      bottomright3 = new ModelRenderer(this, 0, 0);
      bottomright3.addBox(0F, 0F, 0F, 1, 1, 1);
      bottomright3.setRotationPoint(3F, 20F, -0.5F);
      bottomright3.setTextureSize(4, 17);
      bottomright3.mirror = true;
      setRotation(bottomright3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bar.render(f5);
    upperleft.render(f5);
    upperright.render(f5);
    uppermid.render(f5);
    Bottomleft.render(f5);
    bottomright.render(f5);
    bottommid.render(f5);
    Bar1.render(f5);
    upperleft1.render(f5);
    uppermid1.render(f5);
    upperright1.render(f5);
    Bottomleft1.render(f5);
    bottommid1.render(f5);
    bottomright1.render(f5);
    Bar2.render(f5);
    upperleft2.render(f5);
    uppermid2.render(f5);
    upperright2.render(f5);
    Bottomleft2.render(f5);
    bottommid2.render(f5);
    bottomright2.render(f5);
    Bar3.render(f5);
    upperleft3.render(f5);
    uppermid3.render(f5);
    upperright3.render(f5);
    Bottomleft3.render(f5);
    bottommid3.render(f5);
    bottomright3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
