// Date: 6/5/2018 11:56:20 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hexopygate.Telgttatium.models;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHutyveFence extends ModelBase
{
  //fields
    ModelRenderer TopFrame;
    ModelRenderer BottomFrame;
    ModelRenderer Top14;
    ModelRenderer Top12;
    ModelRenderer Top8;
    ModelRenderer Top4;
    ModelRenderer Top2;
    ModelRenderer Bottom14;
    ModelRenderer Bottom12;
    ModelRenderer Bottom8;
    ModelRenderer Bottom4;
    ModelRenderer Bottom2;
    ModelRenderer Top4p2;
    ModelRenderer Bottom4p2;
    ModelRenderer Right2;
    ModelRenderer Right4;
    ModelRenderer Right6;
    ModelRenderer Left2;
    ModelRenderer Left4;
    ModelRenderer Left6;
    ModelRenderer LeftPost;
    ModelRenderer RightPost;
    ModelRenderer TopRightGlass5;
    ModelRenderer BottomLeftGlass5;
    ModelRenderer BottomRightGlass5;
    ModelRenderer TopLeftGlass5;
    ModelRenderer BottomRightGlass1;
    ModelRenderer TopRightGlass1;
    ModelRenderer TopRightGlass2;
    ModelRenderer TopRightGlass2p2;
    ModelRenderer RightGlass;
    ModelRenderer BottomRightGlass2;
    ModelRenderer LeftGlass;
    ModelRenderer BottomRightGlass2p2;
    ModelRenderer BottomLeftGlass2p2;
    ModelRenderer BottomLeftGlass2;
    ModelRenderer BottomLeftGlass1;
    ModelRenderer TopLeftGlass2p2;
    ModelRenderer TopLeftGlass2;
    ModelRenderer TopLeftGlass1;
  
  public ModelHutyveFence()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      TopFrame = new ModelRenderer(this, 0, 0);
      TopFrame.addBox(0F, 0F, 0F, 14, 1, 1);
      TopFrame.setRotationPoint(-7F, 9F, 0F);
      TopFrame.setTextureSize(32, 32);
      TopFrame.mirror = true;
      setRotation(TopFrame, 0F, 0F, 0F);
      BottomFrame = new ModelRenderer(this, 0, 0);
      BottomFrame.addBox(0F, 0F, 0F, 14, 1, 1);
      BottomFrame.setRotationPoint(-7F, 22F, 0F);
      BottomFrame.setTextureSize(32, 32);
      BottomFrame.mirror = true;
      setRotation(BottomFrame, 0F, 0F, 0F);
      Top14 = new ModelRenderer(this, 0, 0);
      Top14.addBox(0F, 0F, 0F, 14, 1, 1);
      Top14.setRotationPoint(-7F, 11F, 0F);
      Top14.setTextureSize(32, 32);
      Top14.mirror = true;
      setRotation(Top14, 0F, 0F, 0F);
      Top12 = new ModelRenderer(this, 0, 0);
      Top12.addBox(0F, 0F, 0F, 12, 1, 1);
      Top12.setRotationPoint(-6F, 12F, 0F);
      Top12.setTextureSize(32, 32);
      Top12.mirror = true;
      setRotation(Top12, 0F, 0F, 0F);
      Top8 = new ModelRenderer(this, 0, 0);
      Top8.addBox(0F, 0F, 0F, 8, 1, 1);
      Top8.setRotationPoint(-4F, 13F, 0F);
      Top8.setTextureSize(32, 32);
      Top8.mirror = true;
      setRotation(Top8, 0F, 0F, 0F);
      Top4 = new ModelRenderer(this, 0, 0);
      Top4.addBox(0F, 0F, 0F, 4, 1, 1);
      Top4.setRotationPoint(-2F, 14F, 0F);
      Top4.setTextureSize(32, 32);
      Top4.mirror = true;
      setRotation(Top4, 0F, 0F, 0F);
      Top2 = new ModelRenderer(this, 0, 0);
      Top2.addBox(0F, 0F, 0F, 2, 1, 1);
      Top2.setRotationPoint(-1F, 15F, 0F);
      Top2.setTextureSize(32, 32);
      Top2.mirror = true;
      setRotation(Top2, 0F, 0F, 0F);
      Bottom14 = new ModelRenderer(this, 0, 0);
      Bottom14.addBox(0F, 0F, 0F, 14, 1, 1);
      Bottom14.setRotationPoint(-7F, 20F, 0F);
      Bottom14.setTextureSize(32, 32);
      Bottom14.mirror = true;
      setRotation(Bottom14, 0F, 0F, 0F);
      Bottom12 = new ModelRenderer(this, 0, 0);
      Bottom12.addBox(0F, 0F, 0F, 12, 1, 1);
      Bottom12.setRotationPoint(-6F, 19F, 0F);
      Bottom12.setTextureSize(32, 32);
      Bottom12.mirror = true;
      setRotation(Bottom12, 0F, 0F, 0F);
      Bottom8 = new ModelRenderer(this, 0, 0);
      Bottom8.addBox(0F, 0F, 0F, 8, 1, 1);
      Bottom8.setRotationPoint(-4F, 18F, 0F);
      Bottom8.setTextureSize(32, 32);
      Bottom8.mirror = true;
      setRotation(Bottom8, 0F, 0F, 0F);
      Bottom4 = new ModelRenderer(this, 0, 0);
      Bottom4.addBox(0F, 0F, 0F, 4, 1, 1);
      Bottom4.setRotationPoint(-2F, 17F, 0F);
      Bottom4.setTextureSize(32, 32);
      Bottom4.mirror = true;
      setRotation(Bottom4, 0F, 0F, 0F);
      Bottom2 = new ModelRenderer(this, 0, 0);
      Bottom2.addBox(0F, 0F, 0F, 2, 1, 1);
      Bottom2.setRotationPoint(-1F, 16F, 0F);
      Bottom2.setTextureSize(32, 32);
      Bottom2.mirror = true;
      setRotation(Bottom2, 0F, 0F, 0F);
      Top4p2 = new ModelRenderer(this, 0, 0);
      Top4p2.addBox(0F, 0F, 0F, 4, 1, 1);
      Top4p2.setRotationPoint(-2F, 10F, 0F);
      Top4p2.setTextureSize(32, 32);
      Top4p2.mirror = true;
      setRotation(Top4p2, 0F, 0F, 0F);
      Bottom4p2 = new ModelRenderer(this, 0, 0);
      Bottom4p2.addBox(0F, 0F, 0F, 4, 1, 1);
      Bottom4p2.setRotationPoint(-2F, 21F, 0F);
      Bottom4p2.setTextureSize(32, 32);
      Bottom4p2.mirror = true;
      setRotation(Bottom4p2, 0F, 0F, 0F);
      Right2 = new ModelRenderer(this, 0, 0);
      Right2.addBox(0F, 0F, 0F, 2, 2, 1);
      Right2.setRotationPoint(-4F, 15F, 0F);
      Right2.setTextureSize(32, 32);
      Right2.mirror = true;
      setRotation(Right2, 0F, 0F, 0F);
      Right4 = new ModelRenderer(this, 0, 0);
      Right4.addBox(0F, 0F, 0F, 2, 4, 1);
      Right4.setRotationPoint(-6F, 14F, 0F);
      Right4.setTextureSize(32, 32);
      Right4.mirror = true;
      setRotation(Right4, 0F, 0F, 0F);
      Right6 = new ModelRenderer(this, 0, 0);
      Right6.addBox(0F, 0F, 0F, 1, 6, 1);
      Right6.setRotationPoint(-7F, 13F, 0F);
      Right6.setTextureSize(32, 32);
      Right6.mirror = true;
      setRotation(Right6, 0F, 0F, 0F);
      Left2 = new ModelRenderer(this, 0, 0);
      Left2.addBox(0F, 0F, 0F, 2, 2, 1);
      Left2.setRotationPoint(2F, 15F, 0F);
      Left2.setTextureSize(32, 32);
      Left2.mirror = true;
      setRotation(Left2, 0F, 0F, 0F);
      Left4 = new ModelRenderer(this, 0, 0);
      Left4.addBox(0F, 0F, 0F, 2, 4, 1);
      Left4.setRotationPoint(4F, 14F, 0F);
      Left4.setTextureSize(32, 32);
      Left4.mirror = true;
      setRotation(Left4, 0F, 0F, 0F);
      Left6 = new ModelRenderer(this, 0, 0);
      Left6.addBox(0F, 0F, 0F, 1, 6, 1);
      Left6.setRotationPoint(6F, 13F, 0F);
      Left6.setTextureSize(32, 32);
      Left6.mirror = true;
      setRotation(Left6, 0F, 0F, 0F);
      LeftPost = new ModelRenderer(this, 0, 0);
      LeftPost.addBox(0F, 0F, 0F, 1, 16, 1);
      LeftPost.setRotationPoint(7F, 8F, 0F);
      LeftPost.setTextureSize(32, 32);
      LeftPost.mirror = true;
      setRotation(LeftPost, 0F, 0F, 0F);
      RightPost = new ModelRenderer(this, 0, 0);
      RightPost.addBox(0F, 0F, 0F, 1, 16, 1);
      RightPost.setRotationPoint(-8F, 8F, 0F);
      RightPost.setTextureSize(32, 32);
      RightPost.mirror = true;
      setRotation(RightPost, 0F, 0F, 0F);
      TopRightGlass5 = new ModelRenderer(this, 7, 18);
      TopRightGlass5.addBox(0F, 0F, 0F, 5, 1, 1);
      TopRightGlass5.setRotationPoint(-7F, 10F, 0F);
      TopRightGlass5.setTextureSize(32, 32);
      TopRightGlass5.mirror = true;
      setRotation(TopRightGlass5, 0F, 0F, 0F);
      BottomLeftGlass5 = new ModelRenderer(this, 7, 18);
      BottomLeftGlass5.addBox(0F, 0F, 0F, 5, 1, 1);
      BottomLeftGlass5.setRotationPoint(2F, 21F, 0F);
      BottomLeftGlass5.setTextureSize(32, 32);
      BottomLeftGlass5.mirror = true;
      setRotation(BottomLeftGlass5, 0F, 0F, 0F);
      BottomRightGlass5 = new ModelRenderer(this, 7, 18);
      BottomRightGlass5.addBox(0F, 0F, 0F, 5, 1, 1);
      BottomRightGlass5.setRotationPoint(-7F, 21F, 0F);
      BottomRightGlass5.setTextureSize(32, 32);
      BottomRightGlass5.mirror = true;
      setRotation(BottomRightGlass5, 0F, 0F, 0F);
      TopLeftGlass5 = new ModelRenderer(this, 7, 18);
      TopLeftGlass5.addBox(0F, 0F, 0F, 5, 1, 1);
      TopLeftGlass5.setRotationPoint(2F, 10F, 0F);
      TopLeftGlass5.setTextureSize(32, 32);
      TopLeftGlass5.mirror = true;
      setRotation(TopLeftGlass5, 0F, 0F, 0F);
      BottomRightGlass1 = new ModelRenderer(this, 7, 18);
      BottomRightGlass1.addBox(0F, 0F, 0F, 1, 1, 1);
      BottomRightGlass1.setRotationPoint(-7F, 19F, 0F);
      BottomRightGlass1.setTextureSize(32, 32);
      BottomRightGlass1.mirror = true;
      setRotation(BottomRightGlass1, 0F, 0F, 0F);
      TopRightGlass1 = new ModelRenderer(this, 7, 18);
      TopRightGlass1.addBox(0F, 0F, 0F, 1, 1, 1);
      TopRightGlass1.setRotationPoint(-7F, 12F, 0F);
      TopRightGlass1.setTextureSize(32, 32);
      TopRightGlass1.mirror = true;
      setRotation(TopRightGlass1, 0F, 0F, 0F);
      TopRightGlass2 = new ModelRenderer(this, 7, 18);
      TopRightGlass2.addBox(0F, 0F, 0F, 2, 1, 1);
      TopRightGlass2.setRotationPoint(-6F, 13F, 0F);
      TopRightGlass2.setTextureSize(32, 32);
      TopRightGlass2.mirror = true;
      setRotation(TopRightGlass2, 0F, 0F, 0F);
      TopRightGlass2p2 = new ModelRenderer(this, 7, 18);
      TopRightGlass2p2.addBox(0F, 0F, 0F, 2, 1, 1);
      TopRightGlass2p2.setRotationPoint(-4F, 14F, 0F);
      TopRightGlass2p2.setTextureSize(32, 32);
      TopRightGlass2p2.mirror = true;
      setRotation(TopRightGlass2p2, 0F, 0F, 0F);
      RightGlass = new ModelRenderer(this, 7, 18);
      RightGlass.addBox(0F, 0F, 0F, 2, 1, 1);
      RightGlass.setRotationPoint(-2F, 17F, 0F);
      RightGlass.setTextureSize(32, 32);
      RightGlass.mirror = true;
      setRotation(RightGlass, 0F, 0F, -1.570796F);
      BottomRightGlass2 = new ModelRenderer(this, 7, 18);
      BottomRightGlass2.addBox(0F, 0F, 0F, 2, 1, 1);
      BottomRightGlass2.setRotationPoint(-6F, 18F, 0F);
      BottomRightGlass2.setTextureSize(32, 32);
      BottomRightGlass2.mirror = true;
      setRotation(BottomRightGlass2, 0F, 0F, 0F);
      LeftGlass = new ModelRenderer(this, 7, 18);
      LeftGlass.addBox(0F, 0F, 0F, 2, 1, 1);
      LeftGlass.setRotationPoint(1F, 17F, 0F);
      LeftGlass.setTextureSize(32, 32);
      LeftGlass.mirror = true;
      setRotation(LeftGlass, 0F, 0F, -1.570796F);
      BottomRightGlass2p2 = new ModelRenderer(this, 7, 18);
      BottomRightGlass2p2.addBox(0F, 0F, 0F, 2, 1, 1);
      BottomRightGlass2p2.setRotationPoint(-4F, 17F, 0F);
      BottomRightGlass2p2.setTextureSize(32, 32);
      BottomRightGlass2p2.mirror = true;
      setRotation(BottomRightGlass2p2, 0F, 0F, 0F);
      BottomLeftGlass2p2 = new ModelRenderer(this, 7, 18);
      BottomLeftGlass2p2.addBox(0F, 0F, 0F, 2, 1, 1);
      BottomLeftGlass2p2.setRotationPoint(2F, 17F, 0F);
      BottomLeftGlass2p2.setTextureSize(32, 32);
      BottomLeftGlass2p2.mirror = true;
      setRotation(BottomLeftGlass2p2, 0F, 0F, 0F);
      BottomLeftGlass2 = new ModelRenderer(this, 7, 18);
      BottomLeftGlass2.addBox(0F, 0F, 0F, 2, 1, 1);
      BottomLeftGlass2.setRotationPoint(4F, 18F, 0F);
      BottomLeftGlass2.setTextureSize(32, 32);
      BottomLeftGlass2.mirror = true;
      setRotation(BottomLeftGlass2, 0F, 0F, 0F);
      BottomLeftGlass1 = new ModelRenderer(this, 7, 18);
      BottomLeftGlass1.addBox(0F, 0F, 0F, 1, 1, 1);
      BottomLeftGlass1.setRotationPoint(6F, 19F, 0F);
      BottomLeftGlass1.setTextureSize(32, 32);
      BottomLeftGlass1.mirror = true;
      setRotation(BottomLeftGlass1, 0F, 0F, 0F);
      TopLeftGlass2p2 = new ModelRenderer(this, 7, 18);
      TopLeftGlass2p2.addBox(0F, 0F, 0F, 2, 1, 1);
      TopLeftGlass2p2.setRotationPoint(2F, 14F, 0F);
      TopLeftGlass2p2.setTextureSize(32, 32);
      TopLeftGlass2p2.mirror = true;
      setRotation(TopLeftGlass2p2, 0F, 0F, 0F);
      TopLeftGlass2 = new ModelRenderer(this, 7, 18);
      TopLeftGlass2.addBox(0F, 0F, 0F, 2, 1, 1);
      TopLeftGlass2.setRotationPoint(4F, 13F, 0F);
      TopLeftGlass2.setTextureSize(32, 32);
      TopLeftGlass2.mirror = true;
      setRotation(TopLeftGlass2, 0F, 0F, 0F);
      TopLeftGlass1 = new ModelRenderer(this, 7, 18);
      TopLeftGlass1.addBox(0F, 0F, 0F, 1, 1, 1);
      TopLeftGlass1.setRotationPoint(6F, 12F, 0F);
      TopLeftGlass1.setTextureSize(32, 32);
      TopLeftGlass1.mirror = true;
      setRotation(TopLeftGlass1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    TopFrame.render(f5);
    BottomFrame.render(f5);
    Top14.render(f5);
    Top12.render(f5);
    Top8.render(f5);
    Top4.render(f5);
    Top2.render(f5);
    Bottom14.render(f5);
    Bottom12.render(f5);
    Bottom8.render(f5);
    Bottom4.render(f5);
    Bottom2.render(f5);
    Top4p2.render(f5);
    Bottom4p2.render(f5);
    Right2.render(f5);
    Right4.render(f5);
    Right6.render(f5);
    Left2.render(f5);
    Left4.render(f5);
    Left6.render(f5);
    LeftPost.render(f5);
    RightPost.render(f5);
    
    GL11.glPushMatrix();
	GL11.glDepthMask(false);
	GL11.glEnable(GL11.GL_BLEND);
	GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE);
    TopRightGlass5.render(f5);
    BottomLeftGlass5.render(f5);
    BottomRightGlass5.render(f5);
    TopLeftGlass5.render(f5);
    BottomRightGlass1.render(f5);
    TopRightGlass1.render(f5);
    TopRightGlass2.render(f5);
    TopRightGlass2p2.render(f5);
    RightGlass.render(f5);
    BottomRightGlass2.render(f5);
    LeftGlass.render(f5);
    BottomRightGlass2p2.render(f5);
    BottomLeftGlass2p2.render(f5);
    BottomLeftGlass2.render(f5);
    BottomLeftGlass1.render(f5);
    TopLeftGlass2p2.render(f5);
    TopLeftGlass2.render(f5);
    TopLeftGlass1.render(f5);
    GL11.glDisable(GL11.GL_BLEND);
    GL11.glDepthMask(true);
    GL11.glPopMatrix();
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
