// Date: 6/3/2018 1:56:36 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.hexopygate.Telgttatium.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWoodenFlowerFence extends ModelBase
{
  //fields
    ModelRenderer StartPlank;
    ModelRenderer Plank1;
    ModelRenderer Plank2;
    ModelRenderer EndPlank;
    ModelRenderer Bar2;
    ModelRenderer Bar;
    ModelRenderer Bar3;
    ModelRenderer HalfFlower;
    ModelRenderer HalfFlower2;
    ModelRenderer Flower;
    ModelRenderer Flower1;
    ModelRenderer Flower2;
    ModelRenderer Flower3;
    ModelRenderer TwoVine;
    ModelRenderer TwoVine2;
    ModelRenderer TwoVine3;
    ModelRenderer ThreeVine;
    ModelRenderer ThreeVine2;
    ModelRenderer ThreeVine3;
    ModelRenderer ThreeVine4;
    ModelRenderer TwoVine4;
    ModelRenderer ThreeVine5;
    ModelRenderer ThreeVine6;
    ModelRenderer ThreeVine7;
    ModelRenderer ThreeVine8;
    ModelRenderer TwoVine5;
    ModelRenderer TwoVine6;
    ModelRenderer TwoVine7;
    ModelRenderer TwoVine8;
    ModelRenderer ThreeVine9;
    ModelRenderer ThreeVine10;
    ModelRenderer ThreeVine11;
    ModelRenderer Vine;
    ModelRenderer TwoVine9;
    ModelRenderer Vine3;
    ModelRenderer Vine2;
    ModelRenderer Vine4;
    ModelRenderer Vine5;
    ModelRenderer ThreeVine12;
  
  public ModelWoodenFlowerFence()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      StartPlank = new ModelRenderer(this, 0, 0);
      StartPlank.addBox(0F, 0F, 0F, 3, 15, 1);
      StartPlank.setRotationPoint(-8F, 9F, 0F);
      StartPlank.setTextureSize(64, 32);
      StartPlank.mirror = true;
      setRotation(StartPlank, 0F, 0F, 0F);
      Plank1 = new ModelRenderer(this, 12, 0);
      Plank1.addBox(0F, 0F, 0F, 4, 15, 1);
      Plank1.setRotationPoint(-4F, 9F, 0F);
      Plank1.setTextureSize(64, 32);
      Plank1.mirror = true;
      setRotation(Plank1, 0F, 0F, 0F);
      Plank2 = new ModelRenderer(this, 12, 0);
      Plank2.addBox(0F, 0F, 0F, 4, 15, 1);
      Plank2.setRotationPoint(1F, 9F, 0F);
      Plank2.setTextureSize(64, 32);
      Plank2.mirror = true;
      setRotation(Plank2, 0F, 0F, 0F);
      EndPlank = new ModelRenderer(this, 25, 0);
      EndPlank.addBox(0F, 0F, 0F, 2, 15, 1);
      EndPlank.setRotationPoint(6F, 9F, 0F);
      EndPlank.setTextureSize(64, 32);
      EndPlank.mirror = true;
      setRotation(EndPlank, 0F, 0F, 0F);
      Bar2 = new ModelRenderer(this, 0, 18);
      Bar2.addBox(0F, 0F, 0F, 16, 1, 1);
      Bar2.setRotationPoint(-8F, 12F, 1F);
      Bar2.setTextureSize(64, 32);
      Bar2.mirror = true;
      setRotation(Bar2, 0F, 0F, 0F);
      Bar = new ModelRenderer(this, 0, 18);
      Bar.addBox(0F, 0F, 0F, 16, 1, 1);
      Bar.setRotationPoint(-8F, 10F, 1F);
      Bar.setTextureSize(64, 32);
      Bar.mirror = true;
      setRotation(Bar, 0F, 0F, 0F);
      Bar3 = new ModelRenderer(this, 0, 22);
      Bar3.addBox(0F, 0F, 0F, 16, 3, 1);
      Bar3.setRotationPoint(-8F, 21F, 1F);
      Bar3.setTextureSize(64, 32);
      Bar3.mirror = true;
      setRotation(Bar3, 0F, 0F, 0F);
      HalfFlower = new ModelRenderer(this, 32, 0);
      HalfFlower.addBox(0F, 0F, 0F, 1, 2, 1);
      HalfFlower.setRotationPoint(-8F, 11F, -1F);
      HalfFlower.setTextureSize(64, 32);
      HalfFlower.mirror = true;
      setRotation(HalfFlower, 0F, 0F, 0F);
      HalfFlower2 = new ModelRenderer(this, 32, 0);
      HalfFlower2.addBox(0F, 0F, 0F, 1, 2, 1);
      HalfFlower2.setRotationPoint(7F, 11F, -1F);
      HalfFlower2.setTextureSize(64, 32);
      HalfFlower2.mirror = true;
      setRotation(HalfFlower2, 0F, 0F, 0F);
      Flower = new ModelRenderer(this, 32, 4);
      Flower.addBox(0F, 0F, 0F, 2, 2, 1);
      Flower.setRotationPoint(-5F, 18F, -1F);
      Flower.setTextureSize(64, 32);
      Flower.mirror = true;
      setRotation(Flower, 0F, 0F, 0F);
      Flower1 = new ModelRenderer(this, 32, 4);
      Flower1.addBox(0F, 0F, 0F, 2, 2, 1);
      Flower1.setRotationPoint(-2F, 13F, -1F);
      Flower1.setTextureSize(64, 32);
      Flower1.mirror = true;
      setRotation(Flower1, 0F, 0F, 0F);
      Flower2 = new ModelRenderer(this, 32, 4);
      Flower2.addBox(0F, 0F, 0F, 2, 2, 1);
      Flower2.setRotationPoint(3F, 17F, -1F);
      Flower2.setTextureSize(64, 32);
      Flower2.mirror = true;
      setRotation(Flower2, 0F, 0F, 0F);
      Flower3 = new ModelRenderer(this, 32, 4);
      Flower3.addBox(0F, 0F, 0F, 2, 2, 1);
      Flower3.setRotationPoint(5F, 12F, -1F);
      Flower3.setTextureSize(64, 32);
      Flower3.mirror = true;
      setRotation(Flower3, 0F, 0F, 0F);
      TwoVine = new ModelRenderer(this, 32, 9);
      TwoVine.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine.setRotationPoint(-7F, 20F, -1F);
      TwoVine.setTextureSize(64, 32);
      TwoVine.mirror = true;
      setRotation(TwoVine, 0F, 0F, 0F);
      TwoVine2 = new ModelRenderer(this, 32, 9);
      TwoVine2.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine2.setRotationPoint(-8F, 21F, -1F);
      TwoVine2.setTextureSize(64, 32);
      TwoVine2.mirror = true;
      setRotation(TwoVine2, 0F, 0F, 0F);
      TwoVine3 = new ModelRenderer(this, 32, 9);
      TwoVine3.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine3.setRotationPoint(-3F, 20F, -1F);
      TwoVine3.setTextureSize(64, 32);
      TwoVine3.mirror = true;
      setRotation(TwoVine3, 0F, 0F, 0F);
      ThreeVine = new ModelRenderer(this, 32, 9);
      ThreeVine.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine.setRotationPoint(-2F, 21F, -1F);
      ThreeVine.setTextureSize(64, 32);
      ThreeVine.mirror = true;
      setRotation(ThreeVine, 0F, 0F, 0F);
      ThreeVine2 = new ModelRenderer(this, 32, 9);
      ThreeVine2.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine2.setRotationPoint(-6F, 18F, -1F);
      ThreeVine2.setTextureSize(64, 32);
      ThreeVine2.mirror = true;
      setRotation(ThreeVine2, 0F, 0F, 0F);
      ThreeVine3 = new ModelRenderer(this, 32, 9);
      ThreeVine3.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine3.setRotationPoint(-7F, 12F, -1F);
      ThreeVine3.setTextureSize(64, 32);
      ThreeVine3.mirror = true;
      setRotation(ThreeVine3, 0F, 0F, 0F);
      ThreeVine4 = new ModelRenderer(this, 32, 9);
      ThreeVine4.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine4.setRotationPoint(-5F, 11F, 2F);
      ThreeVine4.setTextureSize(64, 32);
      ThreeVine4.mirror = true;
      setRotation(ThreeVine4, 0F, 0F, 0F);
      TwoVine4 = new ModelRenderer(this, 32, 9);
      TwoVine4.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine4.setRotationPoint(-4F, 11F, -1F);
      TwoVine4.setTextureSize(64, 32);
      TwoVine4.mirror = true;
      setRotation(TwoVine4, 0F, 0F, 1.570796F);
      ThreeVine5 = new ModelRenderer(this, 32, 9);
      ThreeVine5.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine5.setRotationPoint(-8F, 13F, -1F);
      ThreeVine5.setTextureSize(64, 32);
      ThreeVine5.mirror = true;
      setRotation(ThreeVine5, 0F, 0F, 0F);
      ThreeVine6 = new ModelRenderer(this, 32, 9);
      ThreeVine6.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine6.setRotationPoint(-4F, 13F, 1F);
      ThreeVine6.setTextureSize(64, 32);
      ThreeVine6.mirror = true;
      setRotation(ThreeVine6, 0F, 0F, 0F);
      ThreeVine7 = new ModelRenderer(this, 32, 9);
      ThreeVine7.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine7.setRotationPoint(-3F, 15F, 1F);
      ThreeVine7.setTextureSize(64, 32);
      ThreeVine7.mirror = true;
      setRotation(ThreeVine7, 0F, 0F, 0F);
      ThreeVine8 = new ModelRenderer(this, 32, 9);
      ThreeVine8.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine8.setRotationPoint(-2F, 17F, 1F);
      ThreeVine8.setTextureSize(64, 32);
      ThreeVine8.mirror = true;
      setRotation(ThreeVine8, 0F, 0F, 0F);
      TwoVine5 = new ModelRenderer(this, 32, 9);
      TwoVine5.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine5.setRotationPoint(0F, 20F, 1F);
      TwoVine5.setTextureSize(64, 32);
      TwoVine5.mirror = true;
      setRotation(TwoVine5, -1.570796F, 0F, -1.570796F);
      TwoVine6 = new ModelRenderer(this, 32, 9);
      TwoVine6.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine6.setRotationPoint(-1F, 20F, 1F);
      TwoVine6.setTextureSize(64, 32);
      TwoVine6.mirror = true;
      setRotation(TwoVine6, 0F, 0F, -1.570796F);
      TwoVine7 = new ModelRenderer(this, 32, 9);
      TwoVine7.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine7.setRotationPoint(0F, 20F, -1F);
      TwoVine7.setTextureSize(64, 32);
      TwoVine7.mirror = true;
      setRotation(TwoVine7, 0F, 0F, 0F);
      TwoVine8 = new ModelRenderer(this, 32, 9);
      TwoVine8.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine8.setRotationPoint(1F, 22F, -1F);
      TwoVine8.setTextureSize(64, 32);
      TwoVine8.mirror = true;
      setRotation(TwoVine8, 0F, 0F, 1.570796F);
      ThreeVine9 = new ModelRenderer(this, 32, 9);
      ThreeVine9.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine9.setRotationPoint(4F, 19F, -1F);
      ThreeVine9.setTextureSize(64, 32);
      ThreeVine9.mirror = true;
      setRotation(ThreeVine9, 0F, 0F, 1.570796F);
      ThreeVine10 = new ModelRenderer(this, 32, 9);
      ThreeVine10.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine10.setRotationPoint(0F, 14F, -1F);
      ThreeVine10.setTextureSize(64, 32);
      ThreeVine10.mirror = true;
      setRotation(ThreeVine10, 0F, 1.570796F, 1.570796F);
      ThreeVine11 = new ModelRenderer(this, 32, 9);
      ThreeVine11.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine11.setRotationPoint(-2F, 12F, -1F);
      ThreeVine11.setTextureSize(64, 32);
      ThreeVine11.mirror = true;
      setRotation(ThreeVine11, 0F, 0F, 1.570796F);
      Vine = new ModelRenderer(this, 32, 9);
      Vine.addBox(0F, 0F, 0F, 1, 4, 1);
      Vine.setRotationPoint(1F, 9F, 3F);
      Vine.setTextureSize(64, 32);
      Vine.mirror = true;
      setRotation(Vine, 0F, 1.570796F, 0F);
      TwoVine9 = new ModelRenderer(this, 32, 9);
      TwoVine9.addBox(0F, 0F, 0F, 1, 2, 1);
      TwoVine9.setRotationPoint(1F, 13F, 2F);
      TwoVine9.setTextureSize(64, 32);
      TwoVine9.mirror = true;
      setRotation(TwoVine9, 0F, 1.570796F, 0F);
      Vine3 = new ModelRenderer(this, 32, 9);
      Vine3.addBox(0F, -1F, 0F, 1, 4, 1);
      Vine3.setRotationPoint(2F, 9F, 0F);
      Vine3.setTextureSize(64, 32);
      Vine3.mirror = true;
      setRotation(Vine3, 1.570796F, 1.570796F, 1.570796F);
      Vine2 = new ModelRenderer(this, 32, 9);
      Vine2.addBox(0F, -1F, 0F, 1, 4, 1);
      Vine2.setRotationPoint(1F, 8F, 0F);
      Vine2.setTextureSize(64, 32);
      Vine2.mirror = true;
      setRotation(Vine2, 0F, 1.570796F, 1.570796F);
      Vine4 = new ModelRenderer(this, 32, 9);
      Vine4.addBox(0F, -1F, 0F, 1, 4, 1);
      Vine4.setRotationPoint(4F, 11F, -1F);
      Vine4.setTextureSize(64, 32);
      Vine4.mirror = true;
      setRotation(Vine4, 0F, 0F, 0F);
      Vine5 = new ModelRenderer(this, 32, 9);
      Vine5.addBox(0F, -1F, 0F, 1, 4, 1);
      Vine5.setRotationPoint(5F, 19F, -1F);
      Vine5.setTextureSize(64, 32);
      Vine5.mirror = true;
      setRotation(Vine5, 0F, 0F, 0F);
      ThreeVine12 = new ModelRenderer(this, 32, 9);
      ThreeVine12.addBox(0F, 0F, 0F, 1, 3, 1);
      ThreeVine12.setRotationPoint(8F, 22F, -1F);
      ThreeVine12.setTextureSize(64, 32);
      ThreeVine12.mirror = true;
      setRotation(ThreeVine12, 0F, 0F, 1.570796F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    StartPlank.render(f5);
    Plank1.render(f5);
    Plank2.render(f5);
    EndPlank.render(f5);
    Bar2.render(f5);
    Bar.render(f5);
    Bar3.render(f5);
    HalfFlower.render(f5);
    HalfFlower2.render(f5);
    Flower.render(f5);
    Flower1.render(f5);
    Flower2.render(f5);
    Flower3.render(f5);
    TwoVine.render(f5);
    TwoVine2.render(f5);
    TwoVine3.render(f5);
    ThreeVine.render(f5);
    ThreeVine2.render(f5);
    ThreeVine3.render(f5);
    ThreeVine4.render(f5);
    TwoVine4.render(f5);
    ThreeVine5.render(f5);
    ThreeVine6.render(f5);
    ThreeVine7.render(f5);
    ThreeVine8.render(f5);
    TwoVine5.render(f5);
    TwoVine6.render(f5);
    TwoVine7.render(f5);
    TwoVine8.render(f5);
    ThreeVine9.render(f5);
    ThreeVine10.render(f5);
    ThreeVine11.render(f5);
    Vine.render(f5);
    TwoVine9.render(f5);
    Vine3.render(f5);
    Vine2.render(f5);
    Vine4.render(f5);
    Vine5.render(f5);
    ThreeVine12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
